In [6]:
import pandas as pd
data = pd.read_csv('regression_data.csv', low_memory=False)

In [7]:
data.head()

activity_year                   lei  derived_msa_md state_code  \
0           2020  549300EOHSB7M6IFW844           19660         FL   
1           2020  549300EOHSB7M6IFW844           36740         FL   
2           2020  549300EOHSB7M6IFW844           23540         FL   
3           2020  549300EOHSB7M6IFW844           19660         FL   
4           2020  549300EOHSB7M6IFW844           15980         FL   

   county_code  census_tract conforming_loan_limit derived_loan_product_type  \
0      12127.0  1.212709e+10                     C   Conventional:First Lien   
1      12117.0  1.211702e+10                     C   Conventional:First Lien   
2      12001.0  1.200100e+10                     C   Conventional:First Lien   
3      12035.0  1.203506e+10                     C   Conventional:First Lien   
4      12071.0  1.207104e+10                     C   Conventional:First Lien   

              derived_dwelling_category       derived_ethnicity  ... model_na  \
0  Single Family (1-4 Units):Site-Built  Not Hispanic or Latino  ...      1.0   
1  Single Family (1-4 Units):Site-Built      Hispanic or Latino  ...      1.0   
2  Single Family (1-4 Units):Site-Built  Not Hispanic or Latino  ...      1.0   
3  Single Family (1-4 Units):Site-Built  Not Hispanic or Latino  ...      1.0   
4  Single Family (1-4 Units):Site-Built  Not Hispanic or Latino  ...      1.0   

  dti_manageable  dti_unmanageable  dti_struggling  less20pct_downpayment  \
0            1.0               0.0             1.0                    1.0   
1            1.0               0.0             1.0                    0.0   
2            0.0               1.0             1.0                    1.0   
3            0.0               1.0             1.0                    1.0   
4            1.0               0.0             1.0                    1.0   

   low_lmi  moderate_lmi  middle_lmi  na_lmi  non_desktop  
0      1.0           1.0         0.0     1.0          0.0  
1      1.0           0.0         1.0     1.0          0.0  
2      1.0           1.0         0.0     1.0          0.0  
3      1.0           1.0         0.0     1.0          1.0  
4      1.0           0.0         1.0     1.0          0.0  

[5 rows x 110 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 659889 entries, 0 to 659888
Columns: 110 entries, activity_year to non_desktop
dtypes: float64(44), int64(51), object(15)
memory usage: 553.8+ MB


# Focus On Dummy Variables

In [12]:
df = data.iloc[:,82: ]

In [13]:
df.head()

denied  native  asian  black  pac_islander  female  less_than25  \
0     1.0     1.0    1.0    1.0           1.0     0.0          1.0   
1     1.0     1.0    1.0    1.0           1.0     0.0          0.0   
2     1.0     1.0    1.0    1.0           1.0     0.0          1.0   
3     1.0     1.0    1.0    1.0           1.0     0.0          1.0   
4     1.0     1.0    0.0    1.0           1.0     0.0          1.0   

   between25_34  between45_54  between55_64  ...  model_na  dti_manageable  \
0           1.0           1.0           0.0  ...       1.0             1.0   
1           1.0           1.0           1.0  ...       1.0             1.0   
2           1.0           1.0           0.0  ...       1.0             0.0   
3           1.0           1.0           0.0  ...       1.0             0.0   
4           1.0           1.0           1.0  ...       1.0             1.0   

   dti_unmanageable  dti_struggling  less20pct_downpayment  low_lmi  \
0               0.0             1.0                    1.0      1.0   
1               0.0             1.0                    0.0      1.0   
2               1.0             1.0                    1.0      1.0   
3               1.0             1.0                    1.0      1.0   
4               0.0             1.0                    1.0      1.0   

   moderate_lmi  middle_lmi  na_lmi  non_desktop  
0           1.0         0.0     1.0          0.0  
1           0.0         1.0     1.0          0.0  
2           1.0         0.0     1.0          0.0  
3           1.0         0.0     1.0          1.0  
4           0.0         1.0     1.0          0.0  

[5 rows x 28 columns]

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 659889 entries, 0 to 659888
Data columns (total 28 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   denied                 659889 non-null  float64
 1   native                 659889 non-null  float64
 2   asian                  659889 non-null  float64
 3   black                  659889 non-null  float64
 4   pac_islander           659889 non-null  float64
 5   female                 659889 non-null  float64
 6   less_than25            659889 non-null  float64
 7   between25_34           659889 non-null  float64
 8   between45_54           659889 non-null  float64
 9   between55_64           659889 non-null  float64
 10  between65_74           659889 non-null  float64
 11  greater74              659889 non-null  float64
 12  less30yrs_mortgage     659889 non-null  float64
 13  more30yrs_mortgage     659889 non-null  float64
 14  equifax                659889 non-nu

# Linear Regression

In [19]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
X = np.array(df.iloc[:, 1:])
y = np.array(df.iloc[:, 0])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [22]:
LR = LinearRegression().fit(X_train, y_train)
y_pred_LR = LR.predict(X_test)
print(mean_squared_error(y_test, y_pred_LR))

0.050770405808453566


In [23]:
LR.coef_#denied 1:approve; asian 0 #race > sex

array([ 3.79871225e-02,  2.08693009e-02,  5.30776260e-02,  5.77684451e-02,
       -1.79086001e-03,  1.74352944e-03, -1.18104856e-02,  7.45343523e-03,
        2.21938044e-03, -8.73261655e-03, -5.50608077e-03,  1.06252104e-02,
        5.21799333e-02, -3.46012836e-04,  3.34393122e-03,  3.98460882e-02,
       -2.17678094e-02,  2.03124620e-02, -2.82847409e-03,  1.69139380e-02,
        6.90413127e-01,  1.97003525e-02,  4.36775563e-02,  2.66081923e-02,
        1.00279284e-02,  4.89038910e-01, -2.36079223e-02])

In [124]:
print(mean_squared_error(y_test, y_pred_LR, squared=False))

0.2253228923311024


In [97]:
from sklearn.metrics import median_absolute_error
print(median_absolute_error(y_pred_LR,y_test))

0.04802974002343097


# LinearSVR

In [24]:
from sklearn.svm import LinearSVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
LSVR = make_pipeline(StandardScaler(),LinearSVR(random_state=0, tol=1e-5))
LSVR.fit(X_train, y_train)
y_pred_LSVR = LSVR.predict(X_test)
print(mean_squared_error(y_test, y_pred_LSVR))

0.05760823643873967


In [26]:
LSVR.named_steps['linearsvr'].coef_

array([ 5.29091485e-12,  3.15465164e-12, -1.67758652e-12,  1.63269761e-11,
        8.23653067e-13,  4.94789165e-13,  2.64432330e-12,  2.82824042e-12,
       -1.94623016e-12,  2.08341062e-12,  4.68708853e-12,  1.79321856e-12,
        5.94467353e-12, -3.48850719e-13, -3.59295480e-14,  4.39333333e-12,
       -3.96705770e-12,  2.91554091e-12,  4.98263907e-13,  4.87665459e-13,
        1.71440107e-01,  7.31162412e-13, -5.01099546e-13,  1.11511184e-13,
       -4.94896654e-13,  5.50273611e-13,  7.33848055e-13])

In [125]:
print(mean_squared_error(y_test, y_pred_LSVR, squared=False))

0.24001715863400197


In [99]:
print(median_absolute_error(y_pred_LSVR,y_test))

4.623190719144077e-12


# RandomForestRegressor

In [32]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(max_depth=2, random_state=0)
RFR.fit(X_train, y_train)
y_pred_RFR = RFR.predict(X_test)
print(mean_squared_error(y_test, y_pred_RFR))

0.05114316150324236


In [126]:
print(mean_squared_error(y_test, y_pred_RFR, squared=False))

0.22614853858303474


In [98]:
print(median_absolute_error(y_pred_RFR,y_test))

0.04891968303768324


In [30]:
RFR2 = RandomForestRegressor(max_depth=10, random_state=0)
RFR2.fit(X_train, y_train)
y_pred_RFR2 = RFR2.predict(X_test)
print(mean_squared_error(y_test, y_pred_RFR2))

0.04978947137220367


In [127]:
print(mean_squared_error(y_test, y_pred_RFR2, squared=False))

0.22313554484259937


In [100]:
print(median_absolute_error(y_pred_RFR2,y_test))

0.0478502397957955


# LogisticRegression

In [47]:
from sklearn.linear_model import LogisticRegression
LoR = LogisticRegression(penalty = 'l2', max_iter = 1000000).fit(X_train, y_train)
y_pred_LoR = LoR.predict(X_test)
print(mean_squared_error(y_test, y_pred_LoR))

0.0556979115005235


In [48]:
LoR.coef_

array([[ 0.59400508,  0.39813405,  0.71625831,  0.80448901, -0.03373686,
         0.0358267 , -0.2382735 ,  0.13463879,  0.04676848, -0.1760618 ,
        -0.10390918,  0.19997227,  0.78874583, -0.00735217,  0.06644749,
         0.53682418, -0.55275717,  0.35965812, -0.05106842,  0.32874225,
         4.26769852,  0.4118065 ,  0.70423829,  0.48997276,  0.21508208,
         3.64166717, -0.55337622]])

In [128]:
print(mean_squared_error(y_test, y_pred_LoR, squared=False))

0.23600404975449785


In [104]:
print(median_absolute_error(y_pred_LoR,y_test))

0.0


# Ridge

In [49]:
from sklearn.linear_model import Ridge
Rreg = Ridge(alpha=0.5).fit(X_train, y_train)
y_pred_Rreg = Rreg.predict(X_test)
print(mean_squared_error(y_test, y_pred_Rreg))

0.05077038296322136


In [50]:
Rreg.coef_

array([ 3.79816073e-02,  2.08696498e-02,  5.30796928e-02,  5.77321460e-02,
       -1.79041874e-03,  1.74387207e-03, -1.18105182e-02,  7.45373860e-03,
        2.21984159e-03, -8.73179548e-03, -5.50476315e-03,  1.06247403e-02,
        5.21762844e-02, -3.46139540e-04,  3.34391628e-03,  3.98431287e-02,
       -2.17668334e-02,  2.03122014e-02, -2.83014945e-03,  1.69121870e-02,
        6.90390848e-01,  1.97008823e-02,  4.36733164e-02,  2.66064260e-02,
        1.00264289e-02,  4.88976558e-01, -2.36084141e-02])

In [129]:
print(mean_squared_error(y_test, y_pred_Rreg, squared=False))

0.22532284163666444


In [102]:
print(median_absolute_error(y_pred_Rreg,y_test))

0.04803360551568214


# XGBRegressor

In [58]:
import xgboost as xgb
xgb_model = xgb.XGBRegressor(max_depth = 3,learning_rate = 0.1,n_estimators = 100, n_jobs = -1)
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)
print(mean_squared_error(y_test, y_pred_xgb))

0.04980589695288331


In [59]:
import xgboost as xgb
xgb_model = xgb.XGBRegressor(max_depth = 5,learning_rate = 0.1,n_estimators = 100, n_jobs = -1)
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)
print(mean_squared_error(y_test, y_pred_xgb))

0.04963853306062021


In [60]:
import xgboost as xgb
xgb_model = xgb.XGBRegressor(max_depth = 5,learning_rate = 0.1,n_estimators = 500, n_jobs = -1)
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)
print(mean_squared_error(y_test, y_pred_xgb))

0.049676757810240335


In [63]:
import xgboost as xgb
xgb_model = xgb.XGBRegressor(max_depth = 6,learning_rate = 0.1,n_estimators = 300, n_jobs = -1)
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)
print(mean_squared_error(y_test, y_pred_xgb))

0.049727643295847904


In [66]:
mean_squared_error(y_test, y_pred_xgb, squared=False)

0.22299695804169145

In [103]:
print(median_absolute_error(y_pred_xgb,y_test))

0.044282615184783936
